import type {Metadata} from "next";
import styles from "./layout.module.css";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "About Billionaires",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className={styles.header}>
                    <Link href="/">
                        <h1>Billionaires List</h1>
                    </Link>
                </header>
                <main className={styles.main}>{children}</main>
                <footer className={styles.footer}>
                    <p>© 2024 Billionaires Inc.</p>
                </footer>
            </body>
        </html>
    );
}
